version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: weekly
  - directory: /src/
    package-ecosystem: nuget
    rebase-strategy: auto
    schedule:
      interval: daily
